# Copyright (C) 2021, RTE (http://www.rte-france.com)
# SPDX-License-Identifier: Apache-2.0
---
version: "3.3"
services:
    jenkins:
        build:
            context: ./jenkins
            args:
                dockergid: ${_CI_DOCKER_GID}  # Host docker gid
        restart: unless-stopped
        volumes:
            - /var/jenkins_home:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
            - /tmp:/tmp
            - .:/opt/docker
        ports:
            - "8080:8080/tcp"
            - "50000:50000/tcp"
        network_mode: bridge
    ntp:
        image: cturra/ntp
        network_mode: bridge
        ports:
            - "123:123/udp"
