# Copyright (C) 2021, RTE (http://www.rte-france.com)
# SPDX-License-Identifier: Apache-2.0
---
version: "3.3"
services:
    jenkins:
        build:
            context: ./jenkins
            args:
                dockergid: ${_CI_DOCKER_GID}  # Host docker gid
        restart: unless-stopped
        volumes:
            - /var/jenkins_home:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
            - /tmp:/tmp
            - .:/opt/docker
            - "/etc/timezone:/etc/timezone:ro"
            - "/etc/localtime:/etc/localtime:ro"
        network_mode: host
    ntp:
        image: cturra/ntp
        network_mode: bridge
        restart: unless-stopped
        ports:
            - "123:123/udp"
    rabbitmq:
        image: "rabbitmq:3-management"
        environment:
            RABBITMQ_DEFAULT_VHOST: "/"
        restart: unless-stopped
    mysql:
        image: "mysql:5.7"
        environment:
            MYSQL_DATABASE: "hawkbit"
            MYSQL_USER: "test" # "root" user gives problems
            MYSQL_ALLOW_EMPTY_PASSWORD: "true"
        restart: unless-stopped
    hawkbit:
        image: "hawkbit/hawkbit-update-server:latest-mysql"
        environment:
            - 'SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/hawkbit'
            - 'SPRING_RABBITMQ_HOST=rabbitmq'
            - 'SPRING_RABBITMQ_USERNAME=guest'
            - 'SPRING_RABBITMQ_PASSWORD=guest'
            - 'SPRING_DATASOURCE_USERNAME=root'
            - 'HAWKBIT_SERVER_DDI_SECURITY_AUTHENTICATION_ANONYMOUS_ENABLED=true'
        restart: unless-stopped
        ports:
            - "8081:8080"
